steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ipfs', '.' ]
  # push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/ipfs']
  # deploy to cloud run - ipfs-main
- name: "gcr.io/cloud-builders/gcloud"
  args: ['run', 'deploy', 'ipfs-main', '--image', 'gcr.io/$PROJECT_ID/ipfs', '--region', 'europe-west4', '--allow-unauthenticated', '--platform', 'managed', '--update-env-vars', 'NODE_ENV=prod']
  # set full traffic to latest revision (needed if rollback was performed)
- name: "gcr.io/cloud-builders/gcloud"
  args: ['run', 'services', 'update-traffic', '$REPO_NAME', '--to-latest', '--region', 'europe-west4', '--platform', 'managed']
