services:
  ipfs0:
    container_name: ipfs0
    image: ceramicnetwork/go-ipfs-daemon # @TODO: replace with newly built image
    ports:
      - "8000:8011"
      - "5000:5001"
    volumes:
      - ./data/ipfs0:/data/ipfs

  ipfs1:
    container_name: ipfs1
    image: ceramicnetwork/go-ipfs-daemon
    ports:
      - "8001:8011"
      - "5001:5001"
    volumes:
      - ./data/ipfs1:/data/ipfs

  ipfs2:
    container_name: ipfs2
    image: ceramicnetwork/go-ipfs-daemon
    ports:
      - "8002:8011"
      - "5002:5001"
    volumes:
      - ./data/ipfs2:/data/ipfs
